---
- name: Detecta a Versão do Sistema Operacional, Configura o Zabbix 6.0 LTS e Atualiza
  hosts: 127.0.0.1
  become: yes
  gather_facts: yes

  tasks:
    - name: Avalia qual a Distribuição do Sistema Operacional
      debug:
        msg: "A distribuição detectada é {{ ansible_distribution }}"

    - name: Avalia qual a versão do Sistema Operacional
      debug:
        msg: "A versão detectada é {{ ansible_distribution_version }}"

    - name: Executa tarefas de acordo com a versão do Sistema Operacional
      block:
        - name: Adiciona chave do repositório do Zabbix ao Ubuntu 22.04
          when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version == '22.04'
          apt_key:
            url: https://repo.zabbix.com/zabbix-official-repo.key
            state: present

        - name: Adiciona repositório do Zabbix ao Ubuntu 22.04
          when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version == '22.04'
          apt_repository:
            repo: deb https://repo.zabbix.com/zabbix/6.0/ubuntu {{ ansible_distribution_release }} main
            state: present

        - name: Adiciona chave do repositório do Zabbix ao Ubuntu 20.04
          when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version == '20.04'
          apt_key:
            url: https://repo.zabbix.com/zabbix-official-repo.key
            state: present

        - name: Adiciona repositório do Zabbix ao Ubuntu 20.04
          when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version == '20.04'
          apt_repository:
            repo: deb https://repo.zabbix.com/zabbix/6.0/ubuntu {{ ansible_distribution_release }} main
            state: present

        - name: Adiciona repositório do Zabbix para CentOS 8
          when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '8'
          yum_repository:
            name: zabbix-6.0
            description: Repositório Oficial Zabbix - x86_64
            baseurl: https://repo.zabbix.com/zabbix/6.0/rhel/8/x86_64/
            gpgkey: https://repo.zabbix.com/RPM-GPG-KEY-ZABBIX-Official
            enabled: yes
            gpgcheck: yes

        - name: Adiciona repositório do Zabbix para CentOS 7
          when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'
          yum_repository:
            name: zabbix-6.0
            description: Repositório Oficial Zabbix - x86_64
            baseurl: https://repo.zabbix.com/zabbix/6.0/rhel/7/x86_64/
            gpgkey: https://repo.zabbix.com/RPM-GPG-KEY-ZABBIX-Official
            enabled: yes
            gpgcheck: yes

        - name: Adiciona chave do repositório do Zabbix para Debian 10
          when: ansible_distribution == 'Debian'
          apt_key:
            url: https://repo.zabbix.com/zabbix-official-repo.key
            state: present

        - name: Adiciona repositório do Zabbix para Debian 10
          when: ansible_distribution == 'Debian' and ansible_distribution_version == '10'
          apt_repository:
            filename: zabbix.list
            repo: deb https://repo.zabbix.com/zabbix/6.0/debian/pool/main/z/zabbix-release/ {{ ansible_distribution_release }} main
            state: present

        - name: Adiciona chave do repositório do Zabbix para Debian 11
          when: ansible_distribution == 'Debian'
          apt_key:
            url: https://repo.zabbix.com/zabbix-official-repo.key
            state: present

        - name: Adiciona repositório do Zabbix para Debian 11
          when: ansible_distribution == 'Debian' and ansible_distribution_version == '11'
          apt_repository:
            filename: zabbix.list
            repo: deb https://repo.zabbix.com/zabbix/6.0/debian/pool/main/z/zabbix-release/ {{ ansible_distribution_release }} main
            state: present

        - name: Atualiza Ubuntu 22.04
          when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '22.04'
          apt:
            upgrade: yes
            update_cache: yes

        - name: Atualiza Ubuntu 20.04
          when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '20.04'
          apt:
            upgrade: yes
            update_cache: yes

        - name: Atualiza CentOS 8
          when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '8'
          yum:
            name: '*'
            state: latest

        - name: Atualiza CentOS 7
          when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'
          yum:
            name: '*'
            state: latest

        - name: Atualiza Debian 11
          when: ansible_distribution == 'Debian' and ansible_distribution_version == '11'
          apt:
            upgrade: dist
            update_cache: yes

        - name: Atualiza Debian 10
          when: ansible_distribution == 'Debian' and ansible_distribution_version == '10'
          apt:
            upgrade: dist
            update_cache: yes

        - name: Atualiza outras versões de Sistema Operacional
          when: ansible_distribution not in ['Ubuntu', 'CentOS', 'Debian'] or ansible_distribution_version not in ['22.04', '20.04', '8', '7', '11', '10']
          debug:
            msg: "Não é possível atualizar esta versão do Sistema Operacional"